name: Message Broker CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'message-broker/**'
      - '.github/workflows/message-broker.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'message-broker/**'
      - '.github/workflows/message-broker.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd message-broker
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        cd message-broker
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Test with pytest
      run: |
        cd message-broker
        pytest
    
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Authorize Docker push
      run: |
        gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev
    
    - name: Build and push Docker image
      run: |
        cd message-broker
        docker build -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app-images/message-broker:${{ github.sha }} .
        docker tag ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app-images/message-broker:${{ github.sha }} ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app-images/message-broker:latest
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app-images/message-broker:${{ github.sha }}
        docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app-images/message-broker:latest
    
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: message-broker
        image: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/app-images/message-broker:${{ github.sha }}
        region: ${{ secrets.GCP_REGION }}
        env_vars: |
          TELEGRAM_BOT_URL=${{ secrets.TELEGRAM_BOT_URL }}
          env:
            PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
            REGION: us-central1
            REPOSITORY: app-images
            SERVICE: message-broker
            PUBSUB_TOPIC: messages
            PUBSUB_SUBSCRIPTION: message-broker-sub